require:
 - rubocop-performance
 - rubocop-rspec
AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
Metrics/BlockLength:
  Exclude:
    - 'jahuty.gemspec'
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*.rb'
