require:
 - rubocop-performance
 - rubocop-rspec
AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  Exclude:
    - 'spec/jahuty/system_spec.rb'
Metrics/BlockLength:
  Exclude:
    - 'jahuty.gemspec'
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*.rb'
RSpec/ExampleLength:
  Exclude:
    - 'spec/jahuty/system_spec.rb'
RSpec/MultipleExpectations:
  Exclude:
    - 'spec/jahuty/system_spec.rb'
