version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2
  codecov: codecov/codecov@1.1.3
jobs:
  test-26:
    docker:
      - image: cimg/ruby:2.6.8
    executor: ruby/default
    steps:
      - checkout
      - ruby/bundle-install
      - run:
          name: Run specs
          command: |
            bundle exec rspec --profile 10 \
                              --format RspecJunitFormatter \
                              --out test_results/rspec.xml \
                              --format progress \
                              $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
  test-27:
    docker:
      - image: cimg/ruby:2.7.4
    executor: ruby/default
    steps:
      - checkout
      - ruby/bundle-install
      - run:
          name: Run specs
          command: |
            bundle exec rspec --profile 10 \
                              --format RspecJunitFormatter \
                              --out test_results/rspec.xml \
                              --format progress \
                              $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
  test-26:
    docker:
      - image: cimg/ruby:3.0.2
    executor: ruby/default
    steps:
      - checkout
      - ruby/bundle-install
      - run:
          name: Run rubocop
          command: bundle exec rake rubocop
      - run:
          name: Run specs
          command: |
            bundle exec rspec --profile 10 \
                              --format RspecJunitFormatter \
                              --out test_results/rspec.xml \
                              --format progress \
                              $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
      - store_test_results:
          path: test_results
      - codecov/upload:
          file: ./coverage/coverage.xml

workflows:
  version: 2
  test-ruby-versions:
    jobs:
      - test-26
      - test-27
      - test-30
